SECRET_KEY = "random-secret-key"
MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = "123hijorati2.0"
MYSQL_DATABASE = "class_test"
# MYSQL_PASSWORD = "root123"
# MYSQL_DATABASE = "ecotrack"
